problem:
  environment:
    number_cuboids:
      dynamic: 0
      static: 4
    number_planes: 0
    number_spheres:
      dynamic: 0
      static: 1
  goal:
    goal_definition:
      subgoal0:
        child_link: 1
        desired_position:
        - -0.5
        - 0.8
        epsilon: 0.1
        indices:
        - 0
        - 1
        is_primary_goal: true
        parent_link: 0
        type: staticSubGoal
        weight: 1.5
        low: [-5, -3]
        high: [5, 3]
  joint_limits:
    lower_limits:
    - -6.0
    - -7.5
    upper_limits:
    - 6.0
    - 7.5
  robot_representation:
    collision_links:
      1:
        sphere:
          radius: 0.1
    self_collision_pairs: {}
fabrics:
  limit_geometry: -0.5 / (x ** 1) * (-0.5 * (ca.sign(xdot) - 1)) * xdot ** 2
  limit_finsler: 1.0/(x**2) * (-0.5 * (ca.sign(xdot) - 1)) * xdot**2
  collision_geometry: -1.2 / (x ** 1) * xdot ** 2
  collision_finsler:  1.0/(x**2) * (-0.5 * (ca.sign(xdot) - 1)) * xdot ** 2
  forcing_type: 'speed-controlled'
obstacles:
  box_0:
    geometry:
      length: 5.0
      position:
      - 0.0
      - 6
      - 0.0
      width: 1.0
    type: box
  box_1:
    geometry:
      length: 8.0
      position:
      - 0.0
      - 3.0
      - 0.0
      width: 1.0
    type: box
  box_2:
    geometry:
      length: 3.5
      position:
      - 0.0
      - -0.5
      - 0.0
      width: 2.0
    type: box
  box_3:
    geometry:
      length: 3.5
      position:
      - 0
      - -6
      - 0.0
      width: 1
    type: box
  sphere_0:
    geometry:
      position:
      - -6.0
      - 7.5
      - 0.0
      radius: 1.0
    type: sphere
setup:
  start_list:
    - [-2.7, -5.0]
    - [-3.3, -1.0]
  goal_list:
    - [5.0, 1.0]
    - [3.5, 6.7]
  vel_mag: 3
  n_start: 15
  n_goal: 10
visuals:
  header:
    text: "Invitation to the public defense\nof my PhD thesis"
    position:
      obstacle_name: box_0
      offset: [0, 0]
    fontsize: 9
    rotation: 0
    fontweight: normal
  title:
    text: "Trajectory Generation for Mobile\nManipulators with Differential Geometry"
    position:
      obstacle_name: box_1
      offset: [0, 1.0]
    fontsize: 10
  info:
    text: "11 December 2024\nDefense: 17:30\nLayperson's talk: 17:00\nSenaatszaal\nAula Conference Center\nTU Delft"
    position:
      obstacle_name: box_2
      offset: [0, 0]
    fontsize: 9
    fontweight: normal
  author_info:
    text: "Max Spahn\nm.spahn@tudelft.nl"
    position:
      obstacle_name: box_3
      offset: [0, 0]
    fontsize: 9
    fontweight: normal

